### ISSUE TITLE
CefViewBrowserClient.cpp的228行 auto context = arguments->GetDouble(0); 无法获取到context的值。

### ISSUE THREAD

**Issue by leashi** [CefView/CefViewCore#10]
win10系统下，文件CefViewCore\src\CefView\CefBrowserApp\CefViewBrowserClient.cpp的228行
auto context = arguments->GetDouble(0);
无法获取到context的值，改为：
auto context = arguments->GetInt(0);
是可以的。

**Comment by obiecane** [comment]
同样遇到这个问题，我是这么改了一下，arguments->GetDouble(0); 的地方就可取到值了

`int64_t
CefViewBrowserClient::AsyncExecuteJSCode(CefRefPtr<CefBrowser> browser,
                                         CefRefPtr<CefFrame> frame,
                                         const CefString &code,
                                         const CefString &url,
                                         int64_t contextId) {
    /*
     * Javascript code:
     *
     * window.__report_js_result__(contextId, function() { ... })());
     */
    std::ostringstream codeWrapper;

    // 因为收到的contextId是int64, 传入js中需要使用double承接；所以在数字后面固定拼上.1，这样100就变成100.1了
    codeWrapper << "window.__report_js_result__(" << contextId << ".1 ,function(){" << code << "}());";

    frame->ExecuteJavaScript(codeWrapper.str().c_str(), url, 0);

    return true;
}`

**Comment by obiecane** [comment]
同样遇到这个问题，我是这么改了一下，arguments->GetDouble(0); 的地方就可取到值了

```c++
int64_t
CefViewBrowserClient::AsyncExecuteJSCode(CefRefPtr<CefBrowser> browser,
                                         CefRefPtr<CefFrame> frame,
                                         const CefString &code,
                                         const CefString &url,
                                         int64_t contextId) {
    /*
     * Javascript code:
     *
     * window.__report_js_result__(contextId, function() { ... })());
     */
    std::ostringstream codeWrapper;

    // 因为收到的contextId是int64, 传入js中需要使用double承接；所以在数字后面固定拼上.1，这样100就变成100.1了
    codeWrapper << "window.__report_js_result__(" << contextId << ".1 ,function(){" << code << "}());";

    frame->ExecuteJavaScript(codeWrapper.str().c_str(), url, 0);

    return true;
}
```

**Comment by tishion** [comment]
Fixed：https://github.com/CefView/CefViewCore/commit/7509136988daf020fc16a41d78f8b71f184ce02e
