### ISSUE TITLE
111.2.7+gebf5d6a+chromium-111.0.5563.148 / Chromium 111.0.5563.148版本支持

### ISSUE THREAD

**Issue by L-Super** [CefView/CefViewCore#16]
新版本请问能提供支持吗？
感觉项目很不错，在Qt+CEF场景下。不知道现在能用于生产环境吗？

**Comment by tishion** [comment]
你直接修改[CefConfig.cmake](https://github.com/CefView/CefViewCore/blob/main/CefConfig.cmake) 里面的版本就行了

**Comment by L-Super** [comment]
> 你直接修改[CefConfig.cmake](https://github.com/CefView/CefViewCore/blob/main/CefConfig.cmake) 里面的版本就行了

看到注释，好像新版本支持不太好？https://github.com/CefView/CefViewCore/blob/main/CefConfig.cmake#L12-L17
