### ISSUE TITLE
Build break with cef91

### ISSUE THREAD

**Issue by hcaihao** [CefView/CefViewCore#2]
1>E:\Develop\2019\QCefView\CefViewCore\src\CefView\CefBrowserApp\CefViewBrowserApp.cpp(66,12): error C2039: 'SetSupportedSchemes': is not a member of 'CefCookieManager'
1>E:\Develop\2019\QCefView\CefViewCore\dep\cef_binary_91.1.22+gc67b5dd+chromium-91.0.4472.124_windows32\include/cef_cookie.h(54): message : see declaration of 'CefCookieManager'

See:
https://github.com/cefsharp/CefSharp/issues/3497

**Comment by tishion** [comment]
If you want to use CEF with different version than the one in current repo, please adapt it by yourself. 
No more such questions please.
