### ISSUE TITLE
Drag and drop event problem

### ISSUE THREAD

**Issue by L-Super** [CefView/CefViewCore#21]
当从文件管理器拖动文件到页面进行上传操作时，以下条件总是成立的，每次返回true，则导致无法调用默认的drag处理。
```
if ((mask & DRAG_OPERATION_LINK) && !dragData->IsFragment()) { 
     return true; 
   } 
```
所以，不太理解，这样不是就默认禁用了DND操作了吗？

CEF里描述
```
Return false for default drag handling behavior or true to cancel the drag event.
```
https://github.com/CefView/CefViewCore/blob/52008f12a77996a7281c6516a7aff2696244f663/src/CefView/CefBrowserApp/CefViewBrowserClient_DragHandler.cpp#L22-L33

**Comment by tishion** [comment]
对的，因为最初设计的时候QCefView是作为一个UI组件，就是要禁止用户拖放文件的操作，以及从页面拖拽link出去，如果你拖拽一个link到QCefView那页面就直接跳转了。

你可以帮忙增加一个接口控制是否允许DND操作，例如  
QCefView::setEnabletDragAndDrop(const bool enable);
bool QCefView::isDragAndDropEnabled() const;

**Comment by tishion** [comment]
注意 CefViewBrowserClient::OnDragEnter 只在NCW模式下有效

**Comment by tishion** [comment]
https://github.com/orgs/CefView/projects/1/views/1?layout=board&pane=issue&itemId=31185880

**Comment by L-Super** [comment]
> 注意 CefViewBrowserClient::OnDragEnter 只在NCW模式下有效

这个函数NCW，OSR模式下无法做到通用吗

**Comment by L-Super** [comment]
> 对的，因为最初设计的时候QCefView是作为一个UI组件，就是要禁止用户拖放文件的操作，以及从页面拖拽link出去，如果你拖拽一个link到QCefView那页面就直接跳转了。
> 
> 你可以帮忙增加一个接口控制是否允许DND操作，例如  
> QCefView::setEnabletDragAndDrop(const bool enable);
> bool QCefView::isDragAndDropEnabled() const;
> 

可以的

**Comment by L-Super** [comment]
> 对的，因为最初设计的时候QCefView是作为一个UI组件，就是要禁止用户拖放文件的操作，以及从页面拖拽link出去，如果你拖拽一个link到QCefView那页面就直接跳转了。
> 
> 你可以帮忙增加一个接口控制是否允许DND操作，例如 QCefView::setEnabletDragAndDrop(const bool enable); bool QCefView::isDragAndDropEnabled() const;

功能已经实现了，但是目前有个问题，当拖拽html、md等文件到窗口非接收拖拽文件区域会直接显示该文件
![动画](https://github.com/CefView/CefViewCore/assets/40905056/76a90d59-f1e5-4861-a2e5-e144f6e78fb8)
另外还有一点，`OnDragEnter()`函数在NCW，OSR模式下无法做到通用吗
@tishion

**Comment by L-Super** [comment]
> > 功能已经实现了，但是目前有个问题，当拖拽html、md等文件到窗口非接收拖拽文件区域会直接显示该文件
> 
> 这个就是当时禁用drop操作的原因

这个目前有办法解决吗
