### ISSUE TITLE
CefDownloadHandler

### ISSUE THREAD

**Issue by Signin-or-Signup** [CefView/CefViewCore#3]
suggest add CefDownloadHandler
Thanks!

**Comment by tishion** [comment]
Hi @Signin-or-Signup  thanks for your suggestion, but could you open an PR to contribute this? Welcome your contribution.

**Comment by tishion** [comment]
https://github.com/CefView/CefViewCore/commit/170a08d09668ae65e8ec0b4d34ae765fafaf5dd2
Added
